apiVersion: v2
name: deploy-ktn-chart
description: A Helm chart for deploying applications with deployment, configmaps, external secrets, service, backendconfig, and HPA.
version: 1.0.1
appVersion: "1.0"
maintainers:
  - name: YourName
    email: your-email@example.com
