{{- range .Values.externalSecrets }}
{{- $existingSecret := lookup "external-secrets.io/v1beta1" "ExternalSecret" .Release.Namespace .name -}}
{{- if not $existingSecret }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  metadata:
    namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  refreshInterval: {{ .refreshInterval | default "60s" }}
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: "SecretStore"
  target:
    name: {{ .name }}
    creationPolicy: "Orphan"
  data:
  {{- range .data }}
  - secretKey: {{ .secretKey }}
    remoteRef:
      key: {{ .remoteRef.key }}
      version: {{ .remoteRef.version | default "latest" | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
