{{- range .Values.externalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  refreshInterval: {{ .refreshInterval | default "60s" }}
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: "SecretStore"
  target:
    name: {{ .name }}
    creationPolicy: "Owner"
  data:
  {{- range .data }}
  - secretKey: {{ .secretKey }}
    remoteRef:
      key: {{ .remoteRef.key }}
      version: {{ .remoteRef.version | default "latest" | quote }}
  {{- end }}
---
{{- end }}
