{{- if not (lookup "external-secrets.io/v1beta1" "SecretStore" .Release.Namespace .Values.secretStore.name) }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.secretStore.projectID }}
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: {{ .Values.secretStore.authSecretName }}
            key: {{ .Values.secretStore.authSecretKey }}
{{- end }}
